# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='intro',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
